/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import domainmodel.NhanVien;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.impl.NhanVienServiceImpl;

/**
 *
 * @author Quang Huy
 */
public class PanelNhanVien extends javax.swing.JPanel {
    
    private DefaultTableModel dtm = new DefaultTableModel();
    private List<NhanVien> list = new ArrayList<>();
    private List<NhanVien> listSearch = new ArrayList<>();
    private NhanVienServiceImpl nhanVienServiceImpl = new NhanVienServiceImpl();

    /**
     * Creates new form PanelNhanVien
     */
    public PanelNhanVien() {
        initComponents();
        pnQLNV.setBackground(Color.white);
        pnThongTinNV.setBackground(Color.white);
        pnDanhSachNV.setBackground(Color.white);
        tbNhanVien.setBackground(Color.white);
        String[] header = {"Mã NV", "Tên NV", "Giới tính", "Ngày sinh", "Địa chỉ", "SĐT", "Email", "Trạng thái", "Chức vụ"};
        tbNhanVien.setModel(dtm);
        dtm.setColumnIdentifiers(header);
        list = nhanVienServiceImpl.getAll();
        showData(list);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        pnQLNV = new javax.swing.JPanel();
        pnThongTinNV = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        radioNam = new javax.swing.JRadioButton();
        radioNu = new javax.swing.JRadioButton();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        txtMa = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        radioQuanLy = new javax.swing.JRadioButton();
        radioNhanVien = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        radioDaNghi = new javax.swing.JRadioButton();
        jLabel55 = new javax.swing.JLabel();
        radioDangLamViec = new javax.swing.JRadioButton();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        pnDanhSachNV = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbNhanVien = new javax.swing.JTable();
        jLabel54 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        pnThongTinNV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Nhân Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N

        jLabel46.setText("Mã");

        jLabel47.setText("Họ tên");

        jLabel48.setText("Giới tính");

        buttonGroup1.add(radioNam);
        radioNam.setSelected(true);
        radioNam.setText("Nam");

        buttonGroup1.add(radioNu);
        radioNu.setText("Nữ");

        jLabel49.setText("Ngày sinh");

        jLabel50.setText("Số điện thoại");

        jLabel51.setText("Địa Chỉ");

        jLabel52.setText("Email");

        jLabel53.setText("Chức vụ");

        buttonGroup2.add(radioQuanLy);
        radioQuanLy.setText("Quản lý");

        buttonGroup2.add(radioNhanVien);
        radioNhanVien.setSelected(true);
        radioNhanVien.setText("Nhân Viên");

        btnThem.setBackground(new java.awt.Color(0, 51, 51));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(0, 51, 51));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        buttonGroup3.add(radioDaNghi);
        radioDaNghi.setText("Đã nghỉ việc");

        jLabel55.setText("Trạng thái");

        buttonGroup3.add(radioDangLamViec);
        radioDangLamViec.setSelected(true);
        radioDangLamViec.setText("Đang làm việc");

        javax.swing.GroupLayout pnThongTinNVLayout = new javax.swing.GroupLayout(pnThongTinNV);
        pnThongTinNV.setLayout(pnThongTinNVLayout);
        pnThongTinNVLayout.setHorizontalGroup(
            pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnThongTinNVLayout.createSequentialGroup()
                        .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinNVLayout.createSequentialGroup()
                                .addComponent(jLabel48)
                                .addGap(18, 18, 18)
                                .addComponent(radioNam)
                                .addGap(21, 21, 21)
                                .addComponent(radioNu))
                            .addGroup(pnThongTinNVLayout.createSequentialGroup()
                                .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel47)
                                    .addComponent(jLabel46))
                                .addGap(28, 28, 28)
                                .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMa, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                    .addComponent(txtTen)))
                            .addGroup(pnThongTinNVLayout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNgaySinh)))
                        .addGap(123, 123, 123)
                        .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinNVLayout.createSequentialGroup()
                                .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel52)
                                    .addComponent(jLabel53)
                                    .addComponent(jLabel55))
                                .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnThongTinNVLayout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioDangLamViec)
                                            .addComponent(radioQuanLy))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioNhanVien)
                                            .addComponent(radioDaNghi))
                                        .addGap(0, 106, Short.MAX_VALUE))
                                    .addGroup(pnThongTinNVLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(txtEmail))))
                            .addGroup(pnThongTinNVLayout.createSequentialGroup()
                                .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel50)
                                    .addComponent(jLabel51))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiaChi)
                                    .addComponent(txtSdt)))))
                    .addGroup(pnThongTinNVLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnThongTinNVLayout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(424, 424, 424))
                            .addGroup(pnThongTinNVLayout.createSequentialGroup()
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(269, 269, 269)))))
                .addGap(358, 358, 358))
        );
        pnThongTinNVLayout.setVerticalGroup(
            pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinNVLayout.createSequentialGroup()
                .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnThongTinNVLayout.createSequentialGroup()
                        .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel51)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel52)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel53)
                            .addComponent(radioQuanLy)
                            .addComponent(radioNhanVien)))
                    .addGroup(pnThongTinNVLayout.createSequentialGroup()
                        .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinNVLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel46))
                            .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel50)
                                .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(radioNam)
                            .addComponent(radioNu))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioDangLamViec)
                    .addComponent(jLabel55)
                    .addComponent(radioDaNghi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(pnThongTinNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua))
                .addGap(22, 22, 22))
        );

        jLabel45.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel45.setText("Quản Lý Nhân Viên");

        pnDanhSachNV.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Nhân Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 16))); // NOI18N

        tbNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Họ Và Tên", "Giới Tính", "Ngày Sinh", "Số điện thoại", "Địa Chỉ", "Email", "Tình Trạng"
            }
        ));
        tbNhanVien.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tbNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbNhanVien.setGridColor(new java.awt.Color(0, 0, 0));
        tbNhanVien.setShowGrid(true);
        tbNhanVien.getTableHeader().setReorderingAllowed(false);
        tbNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbNhanVienMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tbNhanVien);

        jLabel54.setText("Tìm kiếm theo");

        txtSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout pnDanhSachNVLayout = new javax.swing.GroupLayout(pnDanhSachNV);
        pnDanhSachNV.setLayout(pnDanhSachNVLayout);
        pnDanhSachNVLayout.setHorizontalGroup(
            pnDanhSachNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDanhSachNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDanhSachNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(pnDanhSachNVLayout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addGap(110, 110, 110)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnDanhSachNVLayout.setVerticalGroup(
            pnDanhSachNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDanhSachNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDanhSachNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel54)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnQLNVLayout = new javax.swing.GroupLayout(pnQLNV);
        pnQLNV.setLayout(pnQLNVLayout);
        pnQLNVLayout.setHorizontalGroup(
            pnQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnQLNVLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addGap(542, 542, 542))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnQLNVLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnDanhSachNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnThongTinNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnQLNVLayout.setVerticalGroup(
            pnQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQLNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnThongTinNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnDanhSachNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        NhanVien nhanVien = getData();
        JOptionPane.showMessageDialog(this, nhanVienServiceImpl.addOrUpdate(nhanVien));
        list = nhanVienServiceImpl.getAll();
        showData(list);
        String email = nhanVien.getEmail();
        guiMail(email);
    }//GEN-LAST:event_btnThemActionPerformed
    
    private NhanVien getData() {
        NhanVien nhanVien = new NhanVien();
        nhanVien.setMa(txtMa.getText());
        nhanVien.setHoTen(txtTen.getText());
        if (radioNam.isSelected()) {
            nhanVien.setGioiTinh(true);
        } else {
            nhanVien.setGioiTinh(false);
        }
        SimpleDateFormat convertToDate = new SimpleDateFormat("dd-MM-yyyy");
        try {
            Date date = convertToDate.parse(txtNgaySinh.getText());
            nhanVien.setNgaySinh(date);
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
        nhanVien.setDiaChi(txtDiaChi.getText());
        nhanVien.setSdt(txtSdt.getText());
        nhanVien.setEmail(txtEmail.getText());
        nhanVien.setMatKhau("123456");
        if (radioDangLamViec.isSelected()) {
            nhanVien.setTrangThai(0);
        } else {
            nhanVien.setTrangThai(1);
        }
        if (radioQuanLy.isSelected()) {
            nhanVien.setChucVu(0);
        } else {
            nhanVien.setChucVu(1);
        }
        nhanVien.setCreatedDate(new Date());
        nhanVien.setLastModifiedDate(new Date());
        return nhanVien;
    }

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        int row = tbNhanVien.getSelectedRow();
        NhanVien nv = list.get(row);
        NhanVien nhanVien = new NhanVien();
        nhanVien.setId(nv.getId());
        nhanVien.setMa(txtMa.getText());
        nhanVien.setHoTen(txtTen.getText());
        if (radioNam.isSelected()) {
            nhanVien.setGioiTinh(true);
        } else {
            nhanVien.setGioiTinh(false);
        }
        SimpleDateFormat convertToDate = new SimpleDateFormat("dd-MM-yyyy");
        try {
            Date date = convertToDate.parse(txtNgaySinh.getText());
            nhanVien.setNgaySinh(date);
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
        nhanVien.setMatKhau(nv.getMatKhau());
        nhanVien.setDiaChi(txtDiaChi.getText());
        nhanVien.setSdt(txtSdt.getText());
        nhanVien.setEmail(txtEmail.getText());
        if (radioDangLamViec.isSelected()) {
            nhanVien.setTrangThai(0);
        } else {
            nhanVien.setTrangThai(1);
        }
        if (radioQuanLy.isSelected()) {
            nhanVien.setChucVu(0);
        } else {
            nhanVien.setChucVu(1);
        }
        nhanVien.setLastModifiedDate(new Date());
        JOptionPane.showMessageDialog(this, nhanVienServiceImpl.addOrUpdate(nhanVien));
        list = nhanVienServiceImpl.getAll();
        showData(list);
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchCaretUpdate
        String search = txtSearch.getText();
        if (search.isEmpty()) {
            showData(list);
        } else {
            List<NhanVien> listSearch = nhanVienServiceImpl.search(search);
            showData(listSearch);
        }
    }//GEN-LAST:event_txtSearchCaretUpdate

    private void tbNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbNhanVienMouseClicked
        // TODO add your handling code here:
        int row = tbNhanVien.getSelectedRow();
        NhanVien nv = list.get(row);
        txtMa.setText(nv.getMa());
        txtTen.setText(nv.getHoTen());
        if (nv.isGioiTinh()) {
            radioNam.setSelected(true);
        } else {
            radioNu.setSelected(true);
        }
        String date;
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        date = dateFormat.format(nv.getNgaySinh());
        txtNgaySinh.setText(date);
        txtDiaChi.setText(nv.getDiaChi());
        txtSdt.setText(nv.getSdt());
        txtEmail.setText(nv.getEmail());
        if (nv.getChucVu() == 0) {
            radioQuanLy.setSelected(true);
        } else {
            radioNhanVien.setSelected(true);
        }
        if (nv.getTrangThai() == 0) {
            radioDangLamViec.setSelected(true);
        } else {
            radioDaNghi.setSelected(true);
        }
    }//GEN-LAST:event_tbNhanVienMouseClicked
    private void showData(List<NhanVien> list) {
        dtm.setRowCount(0);
        for (NhanVien nhanVien : list) {
            dtm.addRow(nhanVien.toDataRow());
        }
    }
    
    private void guiMail(String email) {
        final String username = "laptopgroup3@gmail.com";
        final String password = "lveekscgavporrkq";
        
        Properties prop = new Properties();
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "587");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.starttls.enable", "true"); //TLS

        Session session = Session.getInstance(prop,
                new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });
        
        try {
            
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("from@gmail.com"));
            message.setRecipients(
                    Message.RecipientType.TO,
                    InternetAddress.parse(email)
            );
            message.setSubject("Welcome to Laptop Group 3 Store");
            message.setText("Dear " + email + ", "
                    + "\nCongratulations on being recruited as an employee of Laptop Group 3 Store "
                    + "\nYour default password is: 123456 \nPlease change your password the first time you log in to the system. "
                    + "\nSincerely thank you."
                    + "\nWish you will have a lot of fun when working at our store in the near future.");
            
            Transport.send(message);
            
            System.out.println("Done");
            
        } catch (MessagingException e) {
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel pnDanhSachNV;
    private javax.swing.JPanel pnQLNV;
    private javax.swing.JPanel pnThongTinNV;
    private javax.swing.JRadioButton radioDaNghi;
    private javax.swing.JRadioButton radioDangLamViec;
    private javax.swing.JRadioButton radioNam;
    private javax.swing.JRadioButton radioNhanVien;
    private javax.swing.JRadioButton radioNu;
    private javax.swing.JRadioButton radioQuanLy;
    private javax.swing.JTable tbNhanVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTen;
    // End of variables declaration//GEN-END:variables
}
