/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import custommodel.ThongKeDoanhThuRespone;
import custommodel.ThongKeSanPhamRespone;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.ThongKeService;
import service.impl.ThongKeServiceImpl;

/**
 *
 * @author Đức Hiệu
 */
public class PanelThongKe extends javax.swing.JPanel {

    /**
     * Creates new form PanelThongKe
     */
    private DefaultTableModel dtmSP = new DefaultTableModel();
    private DefaultTableModel dtmDT = new DefaultTableModel();
    private DefaultComboBoxModel dcbmThangNam;
    private ThongKeService serviceThongKe = new ThongKeServiceImpl();
    private List<ThongKeSanPhamRespone> listSP = new ArrayList<>();
    private List<ThongKeDoanhThuRespone> listDT = new ArrayList<>();
    private DateFormat dateFor = new SimpleDateFormat("yyyy/MM/dd");

    public PanelThongKe() throws ParseException {
        initComponents();
        tbDoanhThu.setModel(dtmDT);
        String hearDT[] = {"Mã HĐ", "Mã nv", "Tên NV", "Tổng tiền"};
        dtmDT.setColumnIdentifiers(hearDT);
        tbSanPham.setModel(dtmSP);
        String hearSP[] = {"Mã SP", "Tên SP", "Giá", "Số lượng đã bán", "Doanh thu"};
        dtmSP.setColumnIdentifiers(hearSP);
// tạo date, hiển thị và tắt 
        Date date = new Date();
        DateFormat dateFor = new SimpleDateFormat("yyyy/MM/dd");
        showDataSP(dateFor.format(date));
        lbSanPhamDangKinhDoanh.setText(String.valueOf(serviceThongKe.spKinhDoanh(0)));
        lbSanPhamNgungKinhDoanh.setText(String.valueOf(serviceThongKe.spKinhDoanh(1)));
        cbbLoaiThoiGian.setSelectedIndex(0);
        lbNhapNgayThangNam.setText("Nhập ngày :");
        txtNgayThangNam.setVisible(true);
        cbbThangNam.setVisible(false);
        showDataDoanhThu();
    }

    private void showDataDoanhThu() throws ParseException {
        dtmDT.setRowCount(0);
        Date date = new Date();
        DateFormat dateFor = new SimpleDateFormat("yyyy/MM/dd");
        listDT = serviceThongKe.getAllDoanhThu(dateFor.parse(dateFor.format(date)));
        listDT.forEach(s -> dtmDT.addRow(s.toDataRow()));
        lbTongDoanhThu.setText(serviceThongKe.getDoanhThu());
    }

    private void showDataDoanhThuSortTang() throws ParseException {
        dtmDT.setRowCount(0);
        Date date = new Date();
        DateFormat dateFor = new SimpleDateFormat("yyyy/MM/dd");
        listDT = serviceThongKe.getAllDoanhThuSortTang(dateFor.parse(dateFor.format(date)));
        listDT.forEach(s -> dtmDT.addRow(s.toDataRow()));
        lbTongDoanhThu.setText(serviceThongKe.getDoanhThu());
    }

    private void showDataDoanhThuSortGiam() throws ParseException {
        dtmDT.setRowCount(0);
        Date date = new Date();
        DateFormat dateFor = new SimpleDateFormat("yyyy/MM/dd");
        listDT = serviceThongKe.getAllDoanhThuSortGiam(dateFor.parse(dateFor.format(date)));
        listDT.forEach(s -> dtmDT.addRow(s.toDataRow()));
        lbTongDoanhThu.setText(serviceThongKe.getDoanhThu());
    }

    private void showDataSP(String ngay) throws ParseException {
        dtmSP.setRowCount(0);
        listSP = serviceThongKe.getAllSanPham(dateFor.parse(ngay));
        listSP.forEach(s -> dtmSP.addRow(s.toDataRow()));
    }

    private void showDataSPMonth(int n) throws ParseException {
        dtmSP.setRowCount(0);
        listSP = serviceThongKe.getAllSanPhamMonth(n);
        listSP.forEach(s -> dtmSP.addRow(s.toDataRow()));
    }

    private void showDataSPYear(int n) throws ParseException {
        dtmSP.setRowCount(0);
        listSP = serviceThongKe.getAllSanPhamYear(n);
        listSP.forEach(s -> dtmSP.addRow(s.toDataRow()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSanPham = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        cbbLoaiThoiGian = new javax.swing.JComboBox<>();
        lbNhapNgayThangNam = new javax.swing.JLabel();
        txtNgayThangNam = new javax.swing.JTextField();
        btnLoc = new javax.swing.JButton();
        btnBoLoc = new javax.swing.JButton();
        cbbThangNam = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lbSanPhamDangKinhDoanh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbSanPhamNgungKinhDoanh = new javax.swing.JLabel();
        panelDoanhThuNgay = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDoanhThu = new javax.swing.JTable();
        btnBoLocDT = new javax.swing.JButton();
        cbbSapXepDoanhThu = new javax.swing.JComboBox<>();
        btnLocDT = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbTongDoanhThu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(98, 191, 215));
        setMaximumSize(new java.awt.Dimension(1260, 850));
        setMinimumSize(new java.awt.Dimension(1260, 850));
        setPreferredSize(new java.awt.Dimension(1260, 850));

        panelSanPham.setBackground(new java.awt.Color(98, 191, 215));
        panelSanPham.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doanh thu theo sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Giá", "Đã bán"
            }
        ));
        jScrollPane2.setViewportView(tbSanPham);

        jLabel6.setText("Loại thời gian :");

        cbbLoaiThoiGian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Báo cáo theo ngày", "Báo cáo theo tháng", "Báo cáo theo năm" }));
        cbbLoaiThoiGian.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbLoaiThoiGianItemStateChanged(evt);
            }
        });

        lbNhapNgayThangNam.setText("Nhập ngày tháng năm : ");

        btnLoc.setBackground(new java.awt.Color(204, 204, 204));
        btnLoc.setIcon(new ImageIcon("src/main/img/search.jpg"));
        btnLoc.setText("Lọc");
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        btnBoLoc.setBackground(new java.awt.Color(241, 242, 242));
        btnBoLoc.setIcon(new ImageIcon("src/main/img/quayLaiThongKe.jpg"));
        btnBoLoc.setText("Bỏ lọc");
        btnBoLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoLocActionPerformed(evt);
            }
        });

        cbbThangNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbbThangNam.setMinimumSize(new java.awt.Dimension(64, 22));
        cbbThangNam.setPreferredSize(new java.awt.Dimension(64, 22));

        jPanel1.setBackground(new java.awt.Color(213, 72, 72));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbSanPhamDangKinhDoanh.setBackground(new java.awt.Color(226, 100, 100));
        lbSanPhamDangKinhDoanh.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbSanPhamDangKinhDoanh.setForeground(new java.awt.Color(255, 255, 255));
        lbSanPhamDangKinhDoanh.setText("10");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Số sản phẩm đang kinh doanh");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbSanPhamDangKinhDoanh, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSanPhamDangKinhDoanh)
                .addGap(17, 17, 17))
        );

        jPanel2.setBackground(new java.awt.Color(238, 136, 86));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Số sản phẩm ngừng kinh doanh");

        lbSanPhamNgungKinhDoanh.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbSanPhamNgungKinhDoanh.setForeground(new java.awt.Color(255, 255, 255));
        lbSanPhamNgungKinhDoanh.setText("10");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbSanPhamNgungKinhDoanh, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSanPhamNgungKinhDoanh)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelSanPhamLayout = new javax.swing.GroupLayout(panelSanPham);
        panelSanPham.setLayout(panelSanPhamLayout);
        panelSanPhamLayout.setHorizontalGroup(
            panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSanPhamLayout.createSequentialGroup()
                        .addGroup(panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSanPhamLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbbLoaiThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelSanPhamLayout.createSequentialGroup()
                        .addGroup(panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelSanPhamLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelSanPhamLayout.createSequentialGroup()
                                .addComponent(lbNhapNgayThangNam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbbThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgayThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelSanPhamLayout.createSequentialGroup()
                                .addComponent(btnLoc)
                                .addGap(92, 92, 92)
                                .addComponent(btnBoLoc)
                                .addGap(3, 3, 3)))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        panelSanPhamLayout.setVerticalGroup(
            panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSanPhamLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSanPhamLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLoc)
                            .addComponent(btnBoLoc)))
                    .addGroup(panelSanPhamLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbbLoaiThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNgayThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbNhapNgayThangNam)
                        .addComponent(cbbThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        panelDoanhThuNgay.setBackground(new java.awt.Color(98, 191, 215));
        panelDoanhThuNgay.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doanh thu theo ngày", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        panelDoanhThuNgay.setMaximumSize(new java.awt.Dimension(0, 0));

        tbDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã nhân viên", "Tên nhân viên", "Tổng tiền"
            }
        ));
        jScrollPane1.setViewportView(tbDoanhThu);

        btnBoLocDT.setBackground(new java.awt.Color(241, 242, 242));
        btnBoLocDT.setIcon(new ImageIcon("src/main/img/quayLaiThongKe.jpg"));
        btnBoLocDT.setText("Bỏ lọc");
        btnBoLocDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoLocDTActionPerformed(evt);
            }
        });

        cbbSapXepDoanhThu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tăng dần", "Giảm dần" }));

        btnLocDT.setBackground(new java.awt.Color(204, 204, 204));
        btnLocDT.setIcon(new ImageIcon("src/main/img/search.jpg"));
        btnLocDT.setText("Lọc");
        btnLocDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocDTActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(66, 121, 77));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tổng doanh thu ngày ");

        lbTongDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbTongDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        lbTongDoanhThu.setText("10");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTongDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lbTongDoanhThu)
                .addGap(25, 25, 25))
        );

        jLabel5.setText("Tổng tiền :");

        javax.swing.GroupLayout panelDoanhThuNgayLayout = new javax.swing.GroupLayout(panelDoanhThuNgay);
        panelDoanhThuNgay.setLayout(panelDoanhThuNgayLayout);
        panelDoanhThuNgayLayout.setHorizontalGroup(
            panelDoanhThuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoanhThuNgayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDoanhThuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelDoanhThuNgayLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelDoanhThuNgayLayout.createSequentialGroup()
                        .addGroup(panelDoanhThuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelDoanhThuNgayLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbbSapXepDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnLocDT)
                                .addGap(33, 33, 33)
                                .addComponent(btnBoLocDT)
                                .addGap(12, 12, 12))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        panelDoanhThuNgayLayout.setVerticalGroup(
            panelDoanhThuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDoanhThuNgayLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelDoanhThuNgayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbSapXepDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnLocDT)
                    .addComponent(btnBoLocDT))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(163, 54, 54));
        jLabel4.setText("Thống kê");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelDoanhThuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel4)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDoanhThuNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbLoaiThoiGianItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbLoaiThoiGianItemStateChanged
        Date date = new Date();
        if (cbbLoaiThoiGian.getSelectedIndex() == 0) {
            lbNhapNgayThangNam.setText("Nhập ngày :");
            txtNgayThangNam.setVisible(true);
            cbbThangNam.setVisible(false);
        } else if (cbbLoaiThoiGian.getSelectedIndex() == 1) {
            dcbmThangNam = new DefaultComboBoxModel();
            lbNhapNgayThangNam.setText("Chọn tháng :");
            txtNgayThangNam.setVisible(false);
            cbbThangNam.setVisible(true);
            for (int i = 1; i <= Integer.parseInt(dateFor.format(new Date()).substring(5, 7)); i++) {
                dcbmThangNam.addElement(i);
            }
            cbbThangNam.setModel(dcbmThangNam);
        } else {
            dcbmThangNam = new DefaultComboBoxModel();
            lbNhapNgayThangNam.setText("Chọn năm :");
            txtNgayThangNam.setVisible(false);
            cbbThangNam.setVisible(true);
            int nam = Integer.parseInt(dateFor.format(new Date()).substring(0, 4));
            for (int i = serviceThongKe.thangNamBatDau(); i <= nam; i++) {
                dcbmThangNam.addElement(i);
            }
            cbbThangNam.setModel(dcbmThangNam);
        }
    }//GEN-LAST:event_cbbLoaiThoiGianItemStateChanged

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        Date date = new Date();
        DateFormat dateFor = new SimpleDateFormat("yyyy/MM/dd");
        if (cbbLoaiThoiGian.getSelectedIndex() == 0) {
            if (!txtNgayThangNam.getText().trim().isEmpty()) {
                try {
                    showDataSP(txtNgayThangNam.getText());
                    if (listSP.size() > 0) {
                        JOptionPane.showMessageDialog(this, "Lọc thành công");
                    } else {
                        JOptionPane.showMessageDialog(this, "Không có sản phẩm nào");
                    }
                } catch (ParseException ex) {
                    //Logger.getLogger(PanelThongKe.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày để lọc");
            }
        } else if (cbbLoaiThoiGian.getSelectedIndex() == 1) {
            try {
                showDataSPMonth((int) cbbThangNam.getSelectedItem());
                if (listSP.size() > 0) {
                    JOptionPane.showMessageDialog(this, "Lọc thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Không có sản phẩm nào");
                }
            } catch (ParseException ex) {
                //Logger.getLogger(PanelThongKe.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                showDataSPYear((int) cbbThangNam.getSelectedItem());
                if (listSP.size() > 0) {
                    JOptionPane.showMessageDialog(this, "Lọc thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Không có sản phẩm nào");
                }
            } catch (ParseException ex) {
                //Logger.getLogger(PanelThongKe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLocActionPerformed

    private void btnBoLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoLocActionPerformed
        Date date = new Date();
        DateFormat dateFor = new SimpleDateFormat("yyyy/MM/dd");
        try {
            showDataSP(dateFor.format(date));
        } catch (ParseException ex) {
            Logger.getLogger(PanelThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBoLocActionPerformed

    private void btnLocDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocDTActionPerformed
        if (cbbSapXepDoanhThu.getSelectedIndex() == 0) {
            try {
                showDataDoanhThuSortTang();
                if (listDT.size() > 0) {
                    JOptionPane.showMessageDialog(this, "Lọc thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Không có hóa đơn nào");
                }
            } catch (ParseException ex) {
                Logger.getLogger(PanelThongKe.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            try {
                showDataDoanhThuSortGiam();
                if (listDT.size() > 0) {
                    JOptionPane.showMessageDialog(this, "Lọc thành công");
                } else {
                    JOptionPane.showMessageDialog(this, "Không có hóa đơn nào");
                }
            } catch (ParseException ex) {
                Logger.getLogger(PanelThongKe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLocDTActionPerformed

    private void btnBoLocDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoLocDTActionPerformed
        try {
            showDataDoanhThu();
        } catch (ParseException ex) {
            Logger.getLogger(PanelThongKe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBoLocDTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoLoc;
    private javax.swing.JButton btnBoLocDT;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnLocDT;
    private javax.swing.JComboBox<String> cbbLoaiThoiGian;
    private javax.swing.JComboBox<String> cbbSapXepDoanhThu;
    private javax.swing.JComboBox<String> cbbThangNam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbNhapNgayThangNam;
    private javax.swing.JLabel lbSanPhamDangKinhDoanh;
    private javax.swing.JLabel lbSanPhamNgungKinhDoanh;
    private javax.swing.JLabel lbTongDoanhThu;
    private javax.swing.JPanel panelDoanhThuNgay;
    private javax.swing.JPanel panelSanPham;
    private javax.swing.JTable tbDoanhThu;
    private javax.swing.JTable tbSanPham;
    private javax.swing.JTextField txtNgayThangNam;
    // End of variables declaration//GEN-END:variables

    private boolean Year(Date date) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
