package view;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.awt.Image;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.xml.bind.DatatypeConverter;
import service.QuenMatKhauService;
import service.impl.QuenMatKhauServiceImpl;

/**
 *
 * @author Đức Hiệu
 */
public class ViewDoiMatKhauMoi extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    private QuenMatKhauService quenMKService = new QuenMatKhauServiceImpl();
    public String mail;
    public int checkHienThiMK1 = 0;
    public int checkHienThiMK2 = 0;

    public ViewDoiMatKhauMoi(String email) {
        initComponents();
        setLocationRelativeTo(null);
        txtMatKhauMoi.setBackground(new Color(0, 0, 0, 0));
        txtNhapLaiMatKhauMoi.setBackground(new Color(0, 0, 0, 0));
        this.mail = email;
        anIcon(btnHienMK1);
        anIcon(btnHienMK2);
    }

    // function , constructer icon ẩn / hiện
    private void anIcon(JButton a) {
        ImageIcon privateIcon = new ImageIcon("src/main/img/anquenmk.png");
        Image closeEye = scaleImage(privateIcon.getImage(), 24, 24);
        ImageIcon closeEyeView = new ImageIcon(closeEye);
        a.setIcon(closeEyeView);
    }

    private void hienIcon(JButton a) {
        ImageIcon privateIcon = new ImageIcon("src/main/img/hienquenmk.png");
        Image closeEye = scaleImage(privateIcon.getImage(), 24, 24);
        ImageIcon closeEyeView = new ImageIcon(closeEye);
        a.setIcon(closeEyeView);
    }

    private Image scaleImage(Image image, int w, int h) {
        Image scaled = image.getScaledInstance(w, h, Image.SCALE_SMOOTH);
        return scaled;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblthoat = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNhapLaiMatKhauMoi = new javax.swing.JPasswordField();
        btnDoiMatKhau = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        btnHienMK1 = new javax.swing.JButton();
        btnHienMK2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đổi mật khẩu");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(406, 278));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        lblthoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblthoatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblthoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblthoatMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Đổi mật khẩu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(151, 151, 151)))
                .addComponent(lblthoat)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Mật khẩu mới");

        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Nhập lại mật khẩu mới");

        txtNhapLaiMatKhauMoi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNhapLaiMatKhauMoi.setForeground(new java.awt.Color(51, 51, 51));
        txtNhapLaiMatKhauMoi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        btnDoiMatKhau.setBackground(new java.awt.Color(0, 153, 0));
        btnDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        btnDoiMatKhau.setText("Đổi mật khẩu");
        btnDoiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiMatKhauActionPerformed(evt);
            }
        });

        btnQuayLai.setBackground(new java.awt.Color(255, 51, 51));
        btnQuayLai.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnQuayLai.setForeground(new java.awt.Color(255, 255, 255));
        btnQuayLai.setText("Quay lại");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        txtMatKhauMoi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMatKhauMoi.setForeground(new java.awt.Color(51, 51, 51));
        txtMatKhauMoi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        btnHienMK1.setContentAreaFilled(false);
        btnHienMK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienMK1ActionPerformed(evt);
            }
        });

        btnHienMK2.setContentAreaFilled(false);
        btnHienMK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienMK2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnDoiMatKhau)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtNhapLaiMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnHienMK2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHienMK1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnHienMK1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNhapLaiMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnHienMK2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoiMatKhau)
                    .addComponent(btnQuayLai))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblthoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthoatMouseEntered
        lblthoat.setBackground(Color.red);
        lblthoat.setOpaque(true);
    }//GEN-LAST:event_lblthoatMouseEntered

    private void lblthoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthoatMouseExited
        lblthoat.setBackground(new Color(0, 102, 102));
        lblthoat.setOpaque(true);
    }//GEN-LAST:event_lblthoatMouseExited

    private void lblthoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthoatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblthoatMouseClicked

    private void btnDoiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiMatKhauActionPerformed
        if (txtMatKhauMoi.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "Mật khẩu mới không được để trống");
        } else if (txtNhapLaiMatKhauMoi.getText().trim().isBlank()) {
            JOptionPane.showMessageDialog(this, "Mật khẩu nhập lại không được để trống");
        } else {
            if (txtNhapLaiMatKhauMoi.getText().trim().equalsIgnoreCase(txtMatKhauMoi.getText().trim())) {
                try {
                    String password = txtNhapLaiMatKhauMoi.getText().trim();
                    MessageDigest md = MessageDigest.getInstance("MD5");
                    md.update(password.getBytes());
                    byte[] digest = md.digest();
                    String myHash = DatatypeConverter
                            .printHexBinary(digest).toUpperCase();
                    JOptionPane.showMessageDialog(this, quenMKService.update(myHash, mail));
                    this.dispose();
                    JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập lại");
                    new ViewDangNhap().setVisible(true);
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(ViewDoiMatKhauMoi.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Mật khẩu nhập lại không chính xác");
            }
        }
    }//GEN-LAST:event_btnDoiMatKhauActionPerformed

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        this.dispose();
        new ViewQuenMatKhau().setVisible(true);
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    private void btnHienMK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienMK1ActionPerformed
        if (checkHienThiMK1 == 0) {
            txtMatKhauMoi.setEchoChar(txtMatKhauMoi.getFocusAccelerator());
            hienIcon(btnHienMK1);
            checkHienThiMK1 = 1;
        } else {
            txtMatKhauMoi.setEchoChar('*');
            anIcon(btnHienMK1);
            checkHienThiMK1 = 0;
        }
    }//GEN-LAST:event_btnHienMK1ActionPerformed

    private void btnHienMK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienMK2ActionPerformed
        if (checkHienThiMK2 == 0) {
            txtNhapLaiMatKhauMoi.setEchoChar(txtNhapLaiMatKhauMoi.getFocusAccelerator());
            hienIcon(btnHienMK2);
            checkHienThiMK2 = 1;
        } else {
            txtNhapLaiMatKhauMoi.setEchoChar('*');
            anIcon(btnHienMK2);
            checkHienThiMK2 = 0;
        }
    }//GEN-LAST:event_btnHienMK2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoiMatKhau;
    private javax.swing.JButton btnHienMK1;
    private javax.swing.JButton btnHienMK2;
    private javax.swing.JButton btnQuayLai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblthoat;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtNhapLaiMatKhauMoi;
    // End of variables declaration//GEN-END:variables

}
