/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Image;
import java.util.Properties;
import java.util.Random;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import service.QuenMatKhauService;
import service.impl.QuenMatKhauServiceImpl;

/**
 *
 * @author Đức Hiệu
 */
public class ViewQuenMatKhau extends javax.swing.JFrame {

    private QuenMatKhauService quenMKService = new QuenMatKhauServiceImpl();
    private int maXacThuc;
    private int checkMa = 0;

    /**
     * Creates new form DangNhap
     */
    public ViewQuenMatKhau() {
        initComponents();
        setLocationRelativeTo(null);
        txtTaiKhoan.setBackground(new Color(0, 0, 0, 0));
        txtMaXacThuc.setBackground(new Color(0, 0, 0, 0));
        turnOff();

        anIcon(btnHienMaXacThuc);
    }

    private void anIcon(JButton a) {
        ImageIcon privateIcon = new ImageIcon("src/main/img/anquenmk.png");
        Image closeEye = scaleImage(privateIcon.getImage(), 24, 24);
        ImageIcon closeEyeView = new ImageIcon(closeEye);
        a.setIcon(closeEyeView);
    }

    private void hienIcon(JButton a) {
        ImageIcon privateIcon = new ImageIcon("src/main/img/hienquenmk.png");
        Image closeEye = scaleImage(privateIcon.getImage(), 24, 24);
        ImageIcon closeEyeView = new ImageIcon(closeEye);
        a.setIcon(closeEyeView);
    }

    private Image scaleImage(Image image, int w, int h) {
        Image scaled = image.getScaledInstance(w, h, Image.SCALE_SMOOTH);
        return scaled;
    }

    private void turnOff() {
        lbMaXT.setVisible(false);
        txtMaXacThuc.setVisible(false);
        lbMaXT.setEnabled(false);
        txtMaXacThuc.setEnabled(false);
        btnXacNhan.setVisible(false);
        btnHienMaXacThuc.setVisible(false);
    }

    private void turnOn() {
        lbMaXT.setVisible(true);
        txtMaXacThuc.setVisible(true);
        lbMaXT.setEnabled(true);
        txtMaXacThuc.setEnabled(true);
        btnXacNhan.setVisible(true);
        btnHienMaXacThuc.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        lbMaXT = new javax.swing.JLabel();
        txtMaXacThuc = new javax.swing.JPasswordField();
        btnGuiMa = new javax.swing.JButton();
        btnHuyBo = new javax.swing.JButton();
        btnXacNhan = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblthoat = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnHienMaXacThuc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quên mật  khẩu");
        setResizable(false);

        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Tài khoản");

        txtTaiKhoan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTaiKhoan.setForeground(new java.awt.Color(51, 51, 51));
        txtTaiKhoan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        lbMaXT.setForeground(new java.awt.Color(0, 102, 102));
        lbMaXT.setText("Mã xác thực");

        txtMaXacThuc.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtMaXacThuc.setForeground(new java.awt.Color(51, 51, 51));
        txtMaXacThuc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 153, 153)));

        btnGuiMa.setForeground(new java.awt.Color(0, 102, 102));
        btnGuiMa.setText("Gửi mã");
        btnGuiMa.setToolTipText("");
        btnGuiMa.setBorder(null);
        btnGuiMa.setBorderPainted(false);
        btnGuiMa.setContentAreaFilled(false);
        btnGuiMa.setDefaultCapable(false);
        btnGuiMa.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnGuiMaMouseMoved(evt);
            }
        });
        btnGuiMa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGuiMaMouseExited(evt);
            }
        });
        btnGuiMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiMaActionPerformed(evt);
            }
        });

        btnHuyBo.setBackground(new java.awt.Color(255, 51, 51));
        btnHuyBo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnHuyBo.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyBo.setText("Hủy bỏ");
        btnHuyBo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyBoActionPerformed(evt);
            }
        });

        btnXacNhan.setBackground(new java.awt.Color(0, 153, 0));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        lblthoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblthoatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblthoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblthoatMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quên mật khẩu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(133, 133, 133)))
                .addComponent(lblthoat)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblthoat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnHienMaXacThuc.setIcon(new ImageIcon("src/main/img/hienquenmk.png"));
        btnHienMaXacThuc.setContentAreaFilled(false);
        btnHienMaXacThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienMaXacThucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtMaXacThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHienMaXacThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnGuiMa)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnXacNhan)
                                .addGap(18, 18, 18)
                                .addComponent(btnHuyBo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMaXT, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTaiKhoan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuiMa)
                .addGap(2, 2, 2)
                .addComponent(lbMaXT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaXacThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHienMaXacThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuyBo)
                    .addComponent(btnXacNhan))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuiMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiMaActionPerformed
        if (quenMKService.validateTaiKhoan(txtTaiKhoan.getText().trim()) == null) {
            final String username = "laptopgroup3@gmail.com";
            final String password = "lveekscgavporrkq";
            Properties prop = new Properties();
            prop.put("mail.smtp.host", "smtp.gmail.com");
            prop.put("mail.smtp.port", "587");
            prop.put("mail.smtp.auth", "true");
            prop.put("mail.smtp.starttls.enable", "true"); //TLS
            Session session = Session.getInstance(prop,
                    new Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(username, password);
                }
            });
            try {
                Message message = new MimeMessage(session);
                if (quenMKService.getOne(txtTaiKhoan.getText().trim()).equals("Tài khoản chính xác")) {
                    turnOn();
                    btnGuiMa.setText("Gửi lại mã");
                    JOptionPane.showMessageDialog(this, quenMKService.getOne(txtTaiKhoan.getText().trim()));
                    JOptionPane.showMessageDialog(this, "Đã gửi mã xác thực tới email, "
                            + "nhập mã xác thực để hoàn tất.");
                    message.setFrom(new InternetAddress("laptopgroup3@gmail.com"));
                    message.setRecipients(
                            Message.RecipientType.TO,
                            InternetAddress.parse(txtTaiKhoan.getText().trim())
                    );
                    message.setSubject("Forrgot password");
                    //Lấy ra tên trước @
                    String[] chuoiTen = txtTaiKhoan.getText().trim().split("@");
                    String tenTrongMail = "";
                    for (int i = 0; i < 1; i++) {
                        tenTrongMail = chuoiTen[i];
                    }
                    //random mật khẩu int
                    Random random = new Random();
                    maXacThuc = random.nextInt((9999 - 1111) + 1) + 1111;
                    //System.out.println(maXacThuc);
                    message.setText("Dear " + tenTrongMail + ", you have forgotten your password. "
                            + "Your verification code is " + maXacThuc + ".");
                    Transport.send(message);
                } else {
                    JOptionPane.showMessageDialog(this, quenMKService.getOne(txtTaiKhoan.getText().trim()));
                }
            } catch (MessagingException e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, quenMKService.validateTaiKhoan(txtTaiKhoan.getText().trim()));
        }
    }//GEN-LAST:event_btnGuiMaActionPerformed

    private void btnHuyBoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyBoActionPerformed
        this.dispose();
        new ViewDangNhap().setVisible(true);
    }//GEN-LAST:event_btnHuyBoActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        if (quenMKService.validateMaXacThuc(txtMaXacThuc.getText().trim()) == null) {
            if (Integer.parseInt(txtMaXacThuc.getText().trim()) == maXacThuc) {
                this.dispose();
                JOptionPane.showMessageDialog(this, "Xác nhận thành công, vui lòng đổi mật khẩu mới.");
                ViewDoiMatKhauMoi viewDoiMKMoi = new ViewDoiMatKhauMoi(txtTaiKhoan.getText().trim());
                viewDoiMKMoi.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Mã xác thực sai, vui lòng nhập lại.");
            }
        } else {
            JOptionPane.showMessageDialog(this, quenMKService.validateMaXacThuc(txtMaXacThuc.getText().trim()));
        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnGuiMaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuiMaMouseExited
        btnGuiMa.setForeground(new Color(0, 102, 102, 255));
    }//GEN-LAST:event_btnGuiMaMouseExited

    private void btnGuiMaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuiMaMouseMoved
        btnGuiMa.setForeground(new Color(204, 0, 51));
    }//GEN-LAST:event_btnGuiMaMouseMoved

    private void lblthoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthoatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblthoatMouseClicked

    private void lblthoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthoatMouseEntered
        lblthoat.setBackground(Color.red);
        lblthoat.setOpaque(true);
    }//GEN-LAST:event_lblthoatMouseEntered

    private void lblthoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthoatMouseExited
        lblthoat.setBackground(new Color(0, 102, 102));
        lblthoat.setOpaque(true);
    }//GEN-LAST:event_lblthoatMouseExited

    private void btnHienMaXacThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienMaXacThucActionPerformed
        if (checkMa == 0) {
            txtMaXacThuc.setEchoChar(txtMaXacThuc.getFocusAccelerator());
            hienIcon(btnHienMaXacThuc);
            checkMa = 1;
        } else {
            txtMaXacThuc.setEchoChar('*');
            anIcon(btnHienMaXacThuc);
            checkMa = 0;
        }
    }//GEN-LAST:event_btnHienMaXacThucActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewQuenMatKhau.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewQuenMatKhau.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewQuenMatKhau.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewQuenMatKhau.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewQuenMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuiMa;
    private javax.swing.JButton btnHienMaXacThuc;
    private javax.swing.JButton btnHuyBo;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMaXT;
    private javax.swing.JLabel lblthoat;
    private javax.swing.JPasswordField txtMaXacThuc;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables
}
